apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "status.fullname" . }}-files
  labels:
{{ include "status.labels" . | indent 4 }}
data:
  SeederCommand.php: |-
{{ .Files.Get "files/SeederCommand.php" | indent 4 }}
  seedData.json: |-
{{ toPrettyJson .Values.seedData | indent 4 }}