apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "status.fullname" . }}
  labels:
{{ include "status.labels" . | indent 4 }}
data:
  # database
  DB_HOST: {{ include "status.fullname" . }}-postgresql
  DB_DATABASE: {{ .Values.postgresql.auth.database  }}
  DB_USERNAME: {{ .Values.postgresql.auth.username }}
  DB_PORT: {{ .Values.postgresql.service.ports.postgresql | quote }}
  APP_ENV: {{ default "production" .Values.env.public.APP_ENV | quote }}
  REDIS_HOST: {{ include "status.fullname" . }}-redis-master
{{- with (first .Values.ingress.hosts) }}
  APP_URL: {{ .host }}
{{- end }}
  {{- range $key, $value := .Values.env.public }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}