apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "status.fullname" . }}
  labels:
    {{- include "status.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "status.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config-files: {{ include (print $.Template.BasePath "/configmap-files.yaml") . | sha256sum }}
        checksum/seedercommand: {{ .Files.Get "files/SeederCommand.php" | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "status.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "status.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: {{ .Values.runAsUser }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - sed 's,DemoSeederCommand,SeederCommand,g' -i /var/www/html/app/Console/Kernel.php &> /proc/1/fd/1 && php artisan cachet:seeder --no-interaction &> /proc/1/fd/1
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/ping
              port: http
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/ping
              port: http
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
# For retrieving the db password for postgresql a separate entry is needed to reuse the common secret
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.postgresql.auth.existingSecret }}
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  {{- else }}
                  name: {{ include "status.fullname" . }}-postgresql
                  {{- end }}
                  key: postgresql-password
          envFrom:
            - configMapRef:
                name: {{ include "status.fullname" . }}
          {{- if .Values.existingSecret }}
            - secretRef:
                name: {{ .Values.existingSecret }}
          {{- else }}
            - secretRef:
                name: {{ include "status.fullname" . }}
          {{- end }}
          volumeMounts:
          - name: {{ include "status.fullname" . }}-files
            mountPath: /var/www/html/app/Console/Commands/SeederCommand.php
            subPath: SeederCommand.php
          - name: {{ include "status.fullname" . }}-files
            mountPath: /var/www/html/app/seedData.json
            subPath: seedData.json
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ include "status.fullname" . }}-files
        configMap:
           name: {{ include "status.fullname" . }}-files
           items:
             - key: SeederCommand.php
               path: SeederCommand.php
             - key: seedData.json
               path: seedData.json