name: Kics check on PR
on:
  pull_request:
      branches:
        - main

jobs:
  scan_pr:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@7
    permissions:
      contents: read
    with: 
      chart_path: "."